# Where should we write the GIF?
Output ./docs/vhs/bdk-quorum-network-create.gif

# Set up a 1800x600 terminal with 40px font.
Set FontSize 40
Set Width 1800
Set Height 600
Set PlaybackSpeed 1.0

# Type a command in the terminal.
Type "bdk quorum network create --interactive"
Sleep 3s
Enter

# Run the command by pressing enter.
Sleep 3s
Enter 

Sleep 3s
Enter 

Sleep 3s
Enter 

Sleep 3s
Enter 

# Admire the output for a bit.
Sleep 10s