bdk orderer up \
-n ${ORDERER_ORG_HOSTNAME_ORG0_ORDERER0}.${ORDERER_ORG_DOMAIN_ORG0} \
-n ${ORDERER_ORG_HOSTNAME_ORG0_ORDERER1}.${ORDERER_ORG_DOMAIN_ORG0} \
-n ${ORDERER_ORG_HOSTNAME_ORG1_ORDERER0}.${ORDERER_ORG_DOMAIN_ORG1}
sleep 2

bdk peer up \
-n peer0.${PEER_ORG_DOMAIN_ORG0} \
-n peer1.${PEER_ORG_DOMAIN_ORG0} \
-n peer2.${PEER_ORG_DOMAIN_ORG0} \
-n peer0.${PEER_ORG_DOMAIN_ORG1} \
-n peer0.${PEER_ORG_DOMAIN_ORG2}
sleep 2